### ISSUE TITLE
Add tooltip and tooltip formatting options for the features api inside the toolbox component

### ISSUE THREAD

**Issue by Jivanvl** [apache/incubator-echarts#10202]
### What problem does this feature solve?
It allows for the toolbox features names to have tooltip formats in the same fashion as some chart types, for example:

https://echarts.apache.org/option.html#series-heatmap.tooltip

### What does the proposed API look like?
```
feature: {
  saveAsImage: {
    tooltip: {
      position: ...,
      formatter: ...,
      backgroundColor: ...,
      borderColor: ...,
      borderWidth: ...,
      padding: ...,
      textStyle: ...,
      extraCSSText: ...,
    }
  }
}
```

**Comment by Ovilia** [comment]
We provided two methods to achieve this.
In #10231, more text style options are enabled to provide better control over the style of icon label.
In #10251, we provide a formatter so that user may decide their own DOM structure and CSS style.
Please refer to these two PRs for more detailed information.
