### ISSUE TITLE
Published package.json is missing license field.

### ISSUE THREAD

**Issue by DylanVann** [apache/incubator-echarts#10479]
### Version
4.2.1

### Steps to reproduce
Install `echarts`, check `node_modules/echarts/package.json` for license field.

### What is expected?
The license field to be the same as in the source.

### What is actually happening?
It is not there.

---
I'm not sure how it got excluded during build / publish seeing as it's in the source.

![image](https://user-images.githubusercontent.com/1537615/57807210-b62b4200-772e-11e9-8f13-6e58e43f7039.png)

**Comment by Ovilia** [comment]
It has been fixed in https://github.com/apache/incubator-echarts/pull/9799 , you can see that in current [master branch](https://github.com/apache/incubator-echarts/blob/master/package.json). But 4.2.1 was released from a release branch that was forked from master before this PR. So the license in npm will be fixed in next release.
