### ISSUE TITLE
Plugin system tutorial

### ISSUE THREAD

**Issue by 0c70pu5** [apache/incubator-echarts#10634]
### What problem does this feature solve?
Hi Echarts team!
I have a task to write a custom component for the X axis. I spent little time researching the project code and could not find a way for myself. Could you share the instruction for writing plugins/components? Perhaps somewhere there is a description of the application core?

### What does the proposed API look like?
I do not know what to offer here

**Comment by Ovilia** [comment]
Sorry, I'm afraid we don't have such instructions currently. Mostly because to provide such a document, we have to cover so much detail that it doesn't seem possible right now.
To make a custom axis, the simplest way is to change the source code, add a `XXXAxisView.js` that extends `CartesianAxisView.js` under `src/component/axis`. Then, you should probably need to search for `CartesianAxisView` and replace it when necessary.

**Comment by 0c70pu5** [comment]
@Ovilia  Thanks for the quick response, as well as for the useful information. I think such an instruction could clarify the project for both the team and the developers.

**Comment by 0c70pu5** [comment]
Solution for some components.
[override.zip](https://github.com/apache/incubator-echarts/files/3610418/override.zip)


```javascript
import echarts from 'echarts/lib/echarts';
import 'echarts/lib/component/tooltip';
import 'echarts/lib/chart/line';
import './override/lib/chart/bar';

export {default as createChartConfigs} from './config';
export {
    echarts
}
```
