### ISSUE TITLE
When the line chart data is null, the line sometimes does not break.

### ISSUE THREAD

**Issue by yuchunyu97** [apache/incubator-echarts#10992]
### Version
4.2.1

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xpk2jJqrj9&v=2](https://gallery.echartsjs.com/editor.html?c=xpk2jJqrj9&v=2)

### Steps to reproduce
Open the link to see a line chart where the data for many points on the line is null, but the points are not broken.

### What is expected?
Only points with data can be connected.

### What is actually happening?
There are a lot of null points that are also connected together.

**Comment by yuchunyu97** [comment]
found the reason. When the x-axis is the time axis, the data is not arranged in chronological order, causing confusion during the drawing process.

Resolution: Sort the data in chronological order.

**Comment by yuchunyu97** [comment]
Or can the official sort the data passed in the timeline before drawing?

**Comment by Ovilia** [comment]
There may be some cases that user want to have the line not be in chronological order. So the best way is to sort by yourself when necessary.

**Comment by chenlijun99** [comment]
I think this issue is still open. It happens on chronologically sorted data too, mostly when the data density is high.

Please see this example: https://gallery.echartsjs.com/editor.html?c=xcuRsPaAOP&v=1

You can try to tweak the value of `INTERVAL` at the first line. The greater the value, the less data is generated.

**Comment by chenlijun99** [comment]
@Ovilia Should I open a new issue?
