### ISSUE TITLE
数据长度>=3000时不能正常显示

### ISSUE THREAD

**Issue by jesoonluo** [apache/incubator-echarts#11206]
### Version
4.3.0-rc.2

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x0_E3hkgpw&comment=0](https://gallery.echartsjs.com/editor.html?c=x0_E3hkgpw&comment=0)

### Steps to reproduce
scatter series data 长度>=3000时，不能正常显示

### What is expected?
能正常显示点图

### What is actually happening?
不显示，或闪烁

**Comment by pissang** [comment]
It's because echarts used progressive rendering when the data amount is large.

You can turn it off by setting `progressive` to `0`. https://www.echartsjs.com/en/option.html#series-scatter.progressive

And try [large](https://www.echartsjs.com/en/option.html#series-scatter.large) if  you have performance issue.

**Comment by jesoonluo** [comment]
@pissang thanks for much.
