### ISSUE TITLE
Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.

### ISSUE THREAD

**Issue by CNzxy0820** [apache/incubator-echarts#11365]
### Version
4.3.0-rc.2

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xcpyv2N1ld](https://gallery.echartsjs.com/editor.html?c=xcpyv2N1ld)

### Steps to reproduce
I just use the link copy to my html,but the "globe: { baseTexture,heightTexture  and environment} "will report an error : "Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded." when I commented this three codes,it didn't report error.

### What is expected?
I want use this example in my website

### What is actually happening?
it reported many errors 

---
I download baseTexture,heightTexture  and environment picture in "https://a1115040996.github.io/MyHTML/echarts/3DEarth.html",and put in my folder,and open in default browser, errors are appeared.

**Comment by alex2wong** [comment]
I guess you're experiencing CORS issue in **file protocol**. You should make sure your page and  assets are served by http/https protocol and the client code request assets within the same domain. Otherwise, browser would restrict **cross-domain file** to be manipulated in canvas. 

Opening html file directly in browser can **not** serve assets by http protocol apparently.

you can simply use npm to install `http-server` to serve static files.
```
npm i http-server -g
cd YourFolder
http-server
```

**Comment by CNzxy0820** [comment]
I upload my folder to local server,then I solve this problem，thanks for your answer.
多谢老哥
