### ISSUE TITLE
Pie chart label not shown when animation is disabled

### ISSUE THREAD

**Issue by maliayas** [apache/incubator-echarts#12110]
### Version
4.6.0

### Reproduction link
[https://jsfiddle.net/cLa5db8n/](https://jsfiddle.net/cLa5db8n/)

### Steps to reproduce
Define a basic pie chart and set `animation` to `false`.

### What is expected?
Labels should be displayed on mouse hover.

### What is actually happening?
Labels are not displayed. If I enable animation, then labels are displayed normally.

---
This issue started with 4.3.0 and happens to this day. v4.2.1 [was fine](https://jsfiddle.net/cLa5db8n/1/).

**Comment by Ovilia** [comment]
Thanks for reporting. This is probably a bug.

**Comment by hoangv** [comment]
@maliayas the jsfiddle works with echarts downgraded to 4.2.1, so I wonder if the bug was introduced [with this commit in PieView.js line 205](https://github.com/apache/incubator-echarts/commit/9847233b23a4d5bf65b01ebfb7d5547edb0e11cb#diff-19529e7aaddb5ad8b1b45417c96c8e00R205).  Still looking into it.  Cc. @100pah
