### ISSUE TITLE
Echarts Sankey 对数据一直提示Sankey is a DAG, the original data has cycle!

### ISSUE THREAD

**Issue by babyvip229** [apache/incubator-echarts#12788]
### Version
4.5.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xr3LI5lPST&v=4](https://gallery.echartsjs.com/editor.html?c=xr3LI5lPST&v=4)

### Steps to reproduce
https://gallery.echartsjs.com/editor.html?c=xr3LI5lPST&v=4
直接查看示例地址可以看到结果。谢谢
他一直提示数据“原始数据有周期”。请问这个原始数据有周期是什么原因呢？

### What is expected?
能够正常显示不报错就行。

### What is actually happening?
无法显示出结构，报错：
Sankey is a DAG, the original data has cycle!

**Comment by yanheSu** [comment]
桑基图 是要求一个 有向无环图 的数据结构，你的数据 中 有可能存在 子 数据 指向 父（及以上） 数据的情况

**Comment by babyvip229** [comment]
> 桑基图 是要求一个 有向无环图 的数据结构，你的数据 中 有可能存在 子 数据 指向 父（及以上） 数据的情况

你好，子数据 指向 父（及以上）数据的情况是什么意思呢？
什么情况下会导致数据存在这样的问题呢？
这个数组格式是我这边自己编辑的。没有做过任何的处理的。

**Comment by yanheSu** [comment]
> 你好，子数据 指向 父（及以上）数据的情况是什么意思呢？
> 什么情况下会导致数据存在这样的问题呢？
> 这个数组格式是我这边自己编辑的。没有做过任何的处理的。
【企业微信功能测试组】-> 业务总部 -> 职能总部 -> 【企业微信功能测试组】
用 环形布局 可能会看的清晰一点 https://gallery.echartsjs.com/editor.html?c=xRh8MLaqz7&v=1

**Comment by babyvip229** [comment]
收到，谢谢，环形布局如何配置每个不一样的颜色呢？

**Comment by babyvip229** [comment]
> > 你好，子数据 指向 父（及以上）数据的情况是什么意思呢？
> > 什么情况下会导致数据存在这样的问题呢？
> > 这个数组格式是我这边自己编辑的。没有做过任何的处理的。
> 
> 【企业微信功能测试组】-> 业务总部 -> 职能总部 -> 【企业微信功能测试组】
> 用 环形布局 可能会看的清晰一点 https://gallery.echartsjs.com/editor.html?c=xRh8MLaqz7&v=1

您好，我在和您确认一下，是不是所有的桑基图都不支持环形布局？

**Comment by Ovilia** [comment]
是的

**Comment by dominic-simplan** [comment]
I don't know if I understood everything because I've just ran it though google translate, but wouldn't it be possible to add it as a feature request to allow cycles in the Sankey diagram?
Is there any definition which says a Sankey diagram must be acyclic? I don't think so, and there are many examples online for Sankey diagrams with cycles. Also, it should be technically possible, as there are cyclic Sankey diagrams e.g. for d3.js.

So while it is not possible now, maybe the cyclic support could be added in the future?

**Comment by merdisheva** [comment]
I need to be able to render Sankey diagram with cycles as well.
I see some implementations drawing links in the opposite direction as well as duplicating nodes so that it becomes DAG.
(a.g. drag A->B->C->A with node A displayed twice)
