### ISSUE TITLE
Documentation for tree - series -data. 

### ISSUE THREAD

**Issue by eerenyuan** [apache/incubator-echarts#12865]
### What problem does this feature solve?
It's unclear how to prepare data for "tree" (not tree-map). 
In the documentation, there is no "data" section under tree - sereis. 

I notice that a lof of options that is available in other view types (e.g. tree-map) is not working in tree. 

### What does the proposed API look like?
similar to other view type, a section to explain how to prepare data for "tree" views, especially it's unique features.

**Comment by plainheart** [comment]
Sorry for the lack of a description about how to prepare data of tree series in English documentation. We will add it soon.

**Comment by plainheart** [comment]
Fixed in https://github.com/apache/incubator-echarts-doc/commit/e387a7404ebc6f83a6f09e9e0ed5d73c5849aa9e

Related updates of online documentation may need to wait until ECharts 4.9.0 releases. 
If you can't wait to read the latest documentation, it's suggested to clone the [documentation repository](https://github.com/apache/incubator-echarts-doc) and then run it according to the [README](https://github.com/apache/incubator-echarts-doc#document-content-development).

Here is a screenshot

![image](https://user-images.githubusercontent.com/26999792/86073632-bdd6b300-bab6-11ea-8db6-7c9f4ac22d06.png)

**Comment by plainheart** [comment]
Hi, @eerenyuan It is online now~ https://echarts.apache.org/en/option.html#series-tree.data

**Comment by eerenyuan** [comment]
thanks, thats' fast.
