### ISSUE TITLE
Hide symbols but show labels.

### ISSUE THREAD

**Issue by aseemgautam** [apache/incubator-echarts#12918]
### What problem does this feature solve?
In my case I only want to show the 1st & the last label. I am able to hide labels using the formatter function but empty symbols (small circles) make the UI very weird. Setting `showAllSymbol` to `false` hide the labels. Setting the `size` to 0 also hides the labels.

Is it possible to show only labels but no symbols?

### What does the proposed API look like?
The API is already there. If Labels.show is `true` & `showAllSymbol: false`, show labels but hide the symbols.

<img width="198" alt="Screenshot 2020-07-07 at 1 31 18 AM" src="https://user-images.githubusercontent.com/3583020/86636199-a1c09d80-bff1-11ea-9590-8fe6d2db77ef.png">

**Comment by plainheart** [comment]
Do you mean you want to hide the empty circles? It's easy to do by using [`symbol: 'none'`](https://echarts.apache.org/en/option.html#series-line.symbol).

**Comment by plainheart** [comment]
It seems that there is no simple way to achieve such requirement, but here is a workaround for you https://gallery.echartsjs.com/editor.html?c=xIJyAD4BFw&v=1

**Comment by aseemgautam** [comment]
Simple enough. `symbol: null`. Works well. Thanks

**Comment by aseemgautam** [comment]
The solution introduces a small bug when using `Legend`.
```
itemStyle: {
            color: 'transparent'
        },
```
Legend icon is now not visible as it respects the `color` setting of `itemStyle`.

https://gallery.echartsjs.com/editor.html?c=xIJyAD4BFw&v=4

**Comment by plainheart** [comment]
Yes, the legend doesn't display normally because of the transparent item color.

Though we can set `legend.itemStyle.color`(Note that this option is not listed in the documentation) as the color we want, but the symbol of the legend will only display a circle but not display the line at the two sides of the circle. This may be not what you want.

Therefore, maybe we can try another way, such as using a very small `symbolSize`.

https://gallery.echartsjs.com/editor.html?c=xIJyAD4BFw&v=5

But there will be an empty circle in the legend, which is hidden in the line series. In addition, the labels will be unclickable and can't respond to the hovering event for the very small symbol size. Will that be acceptable?
