### ISSUE TITLE
ECharts 3 renders line charts two times slower than ECharts 2

### ISSUE THREAD

**Issue by revov** [apache/incubator-echarts#2642]
In addition to the rich feature set _ECharts_ seems to be one of the best charting libraries when it comes to performance with large data sets. However after doing some comparisons between version 2 and 3 it seems that the render times of line charts have increased significantly (especially on firefox) since v2.2.7

Here is my setup:
50 charts, each with 20 series of 1000 points with data gaps.

|  | Linux Chrome | Linux Firefox |
| --- | --- | --- |
| [echarts2 fiddle](https://jsfiddle.net/Lr56v6t8/1/) | 4.9s | 9.5s |
| [echarts3 fiddle](http://jsfiddle.net/kxotynLc/1/) | 9s | 19s |

I have tried to optimize the echarts3 fiddle as much as possible but the times did not improve. I couldn't spot any significant changes in the interactivity of the line graphs that could justify the slower rendering speed. Are there any new functionality/animations that require the increase in the loading time and is there a way to disable them in version 3?

**Comment by pissang** [comment]
Thanks for the feedback. Maybe it is because in 2.0 line points will be sampled if data count is larger than the width pixel count. But in 3.0 we haven't add this feature yet. I can try your demo again after adding this feature and give you the new results, which will be in next version, I think.

And for your case, which has many chart instance in one page, we have actually do some optimization to reduce the created canvas element. Maybe you can find it is much smoother when scrolling the page in version 3

**Comment by murliatdure** [comment]
+1

**Comment by AngryElephant** [comment]
Any improvement ?

**Comment by piyushgupta1** [comment]
+1
