### ISSUE TITLE
Issues with tooltip.showDelay

### ISSUE THREAD

**Issue by JeffreyRoosendaal** [apache/incubator-echarts#3243]
I was really waiting for a `tooltip.showDelay` option, so first, thanks for adding it!

But, I have two issues with it though. They're not bugs, it's how it works/reacts.
- What was always bugging me a little, was that when hovering a chart and triggering the tooltip, the tooltip sort of 'flies' from the last location where it was visible. I think this is not really bad per se, but when triggering the tooltip for the first time, it flies from the bottom right corner right to your mouse cursor. This looks a little weird, and when placing a small chart (like a sparkline) at the very right side of your page, it triggers a horizontal scrollbar for a very short instance. What I hoped was when using the `showDelay` options, the tooltip flies to the correct location (your cursor) in the background (invisible), thereby skipping the flying animation, and then pops up (fades in) after the specified `showDelay` time. However it just delays the flying animation.
- The other thing is that when using the `showDelay` option, it not only delays the initial trigger time (which is correct behaviour) it also delays the tooltip while it's already triggered and you're hovering over multiple datapoints. Which is not correct behaviour I think. I want to delay the tooltip a little, so it doesn't trigger every time you move your mouse over the chart (because that's kind of annoying if you have lots of charts on a page). But once it's triggered, it should act like it normally would; without a delay. It makes it look/behave kind of unresponsive, and is enough reason for me to not use `showDelay`.

**Comment by pissang** [comment]
Hi @JeffreyRoosendaal , thanks for the advise firstly.

About the second one. At first we add showDelay because in some case developer will add link in the tooltip. And without showDelay user may be hard to enter the tooltip and click the link since the tooltip will always move beside the mouse position. So we add a showDelay to avoid that situation. 

I agree that it is really annoying. But i can't figure out a better way. And suggestions are always welcome. Thanks again:)
