### ISSUE TITLE
dataZoom data shadow is rendered incorrectly when showing time series with non-linear data

### ISSUE THREAD

**Issue by jarben** [apache/incubator-echarts#3691]
Version: 3.2.2

Example:
![image](https://cloud.githubusercontent.com/assets/561365/17022482/71b1b92a-4f4e-11e6-8c6a-f5e0b45eebe2.png)

The line graph shows a big jump in the beginning of the line, where the dataZoom slowly grows.

Code attached:
[dataZoom.zip](https://github.com/ecomfe/echarts/files/375937/dataZoom.zip)

**Comment by ptulou** [comment]
Hello, I was wondering what the decision on this was. I ran into this as well where we have some high-frequency data on one end and it skews the shadow shown in the dataZoom. The dataZoom seems to be spacing all the points at regular intervals rather than according to their x-values. Is there a way to get the dataZoom to honor the x values that I can use today or is there a plan to address this in the future? Thanks for your guidance!

**Comment by xLarry** [comment]
I am facing this issue as well :(

Looks like it has been reported again in https://github.com/apache/echarts/issues/8186 but I cannot see any activity there as well.

**Comment by Dznan** [comment]
It has been 6 years and over 2 versions. Is it hard to fix it?

**Comment by Ovilia** [comment]
@Dznan I'm fixing this. Please follow #17143
