### ISSUE TITLE
Image background for chart

### ISSUE THREAD

**Issue by nzjrs** [apache/incubator-echarts#4005]
#### 问题简述 (One-line summary)

I would like to add an image background to my chart (like a photo). I couldn't find any documentation how to do this. Should I use `chart.getZr() and then add a zrender.shapes.Image()`, or there was a way with `echarts.graphics.Image()`?
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): Echarts v3
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
You can use css to add background to the container.

**Comment by nzjrs** [comment]
Im trying to make a line plot over the image showing how something in the
image moved (think computer vision tracking). For that I really need the
image to be only the background of the chart as I want to plot x,y in image
pixel coordinates.

Css background is for the whole plot.

**Comment by shivamsriva31093** [comment]
Hi @nzjrs Did you solve this issue? I am doing a very similar thing and stuck at image coordinate transfornation.

**Comment by ChrizZz110** [comment]
I also looking for such a feature. I want to have an image of a map behind an eCharts graph. If I zoom in, the image should be also zoomed. If I move the graph, the image also should move.

**Comment by urgrund** [comment]
> I also looking for such a feature. I want to have an image of a map behind an eCharts graph. If I zoom in, the image should be also zoomed. If I move the graph, the image also should move.

Exactly the same here,  I've scoured the docs and examples it seems the only way is to register an SVG
Surprised we can't just provided a regular image with relative scaling to the data.

**Comment by joshinger** [comment]
I also looking for such feature. CSS only works if you set an id for the container. There is no id.

**Comment by larissac-bb** [comment]
> I also looking for such a feature. I want to have an image of a map behind an eCharts graph. If I zoom in, the image should be also zoomed. If I move the graph, the image also should move.

Same here, did someone figure it out?

**Comment by urgrund** [comment]
I think since it's marked as 'Closed'  no one from eCharts team will look at this?  _(even though the CSS suggestion doesn't address the requested functionality)_

There is some really long winded approach that I got half working but abandoned 
- create a relatively positioned div that fills the same area are your chart div
- make the padding match the grid of your chart _(if all you wanted was a static background, you can stop here)_

- hook into the 'onzoom' callback of a zoom in your echart 
- use the values of the zoom _(annoyingly the zoom data changes if it were a mousewheel or a drag even though ultimately they are just percentages)_  to feed back into the image div and manipluate image background of the div.

Something like 
```
chartContainer.style.backgroundSize = (100 / zoomX) + '% ' + (100 / zoomY) + '%';
chartContainer.style.backgroundPosition = (-offsetX / zoomX) + 'px ' + (-offsetY / zoomY) + 'px';
```

It was too convoluted to get it finished though -   if eCharts simply allowed an image as well as svg for backgrounds in scatter/map type charts this would solve it :)

**Comment by larissac-bb** [comment]
> Exactly the same here, I've scoured the docs and examples it seems the only way is to register an SVG Surprised we can't just provided a regular image with relative scaling to the data.

So it works for SVGs (with dragging and zooming)? Would I use the "graphic" option for that?
