### ISSUE TITLE
饼图label超出边界，label被遮挡，但是labelLine还在

### ISSUE THREAD

**Issue by go299** [apache/incubator-echarts#6238]
### One-line summary [问题简述]
当数据比较多的时候，图形显示区域比较小的时候，一些label会越界，只能显示labelline.
可以加校验吗，如果label 越界，labelline也不显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.1.6
+ Browser version [浏览器类型和版本]: chrome 59
+ OS Version [操作系统类型和版本]: win 10

### Expected behaviour [期望结果]
label越界不显示labelline和label

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by CWSchen** [comment]
你外面包一个div，然后设置一个 overflow：hidden 试试

**Comment by go299** [comment]
不行，labellines是在canvas区域内显示的

**Comment by Shawnhoo666** [comment]
请问楼主最后是如何解决的呢？我也遇到了同样问题

**Comment by 100pah** [comment]
如果饼图扇区非常多导致 label 非常多，那么往往每个扇区都比较小，导致并不易于看清楚。
如果对比较小的扇区进行合并，统一显示一个 label，会不会效果好些？

**Comment by pursuitM** [comment]
楼主最后是怎么解决的，遇到了同样的问题

**Comment by zhangya5847** [comment]
遇到同样的问题，还会出现label上面被切掉一半的情况。
![image](https://user-images.githubusercontent.com/15855773/33411770-62aac894-d5c2-11e7-8470-7c5c4e430513.png)

**Comment by davinma** [comment]
推荐修改 startAngle 的起始角度值，让图表重新摆放 label 的位置 。

**Comment by Paul-Kijtapart** [comment]
Hi there,

**Problem**
I run into similar issue with label overflowing the donut-chart. 

**Problem**
JsFiddle: http://jsfiddle.net/coolbean/cj31rtpf/418/
In the jsFiddle, you can see one long name in the data "aaaaaaaaaaaaaaaaaa", which will be used as "label" for the chart.
Since the name is really long, its length will exceeds the donut (overflowing).

**What I expect**
if the label is too big for the wrapping circle, its label text should : 
1. be displayed as "aaa..." where "..." implies overflowing.
- when user hover over the label, the full text will be displayed.
OR
2. be broken into multiple lines based on user specified width and height fields on the label option. When a line exceeds the specified width, the text will start on the new line.

**Possible solution**
My current workaround are:
1. Limit the size/content of the label via label.formatter.

**Question**
I am wondering if there is an Echart option to handle this case.

**Comment by airwin** [comment]
try #8513

**Comment by zhoufanglu** [comment]
最后解决了么 ？ 我遇到了相同的问题

**Comment by gefangshuai** [comment]
> 推荐修改 startAngle 的起始角度值，让图表重新摆放 label 的位置 。

正解！👍

**Comment by JSjump** [comment]
> startAngle
这样数据一旦变化又会有问题

**Comment by CoolWind0719** [comment]
> > startAngle
> > 这样数据一旦变化又会有问题

是这样，希望能有个更完善的解决办法
