### ISSUE TITLE
Pie Chart Disappears On Resize

### ISSUE THREAD

**Issue by rkellermeyer** [apache/incubator-echarts#6864]
### Pie Chart Disappears On Resize [问题简述]

I'm using echarts within gridster.js.
When I resize the pie chart, the chart is cutoff by the curved edge of the canvas.

![screen shot 2017-10-18 at 4 00 07 pm](https://user-images.githubusercontent.com/775824/31742583-ade33dd0-b41d-11e7-9ca0-61e0e5e63822.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: MacOS 10.12.6

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by lianliu22** [comment]
We are using 4.0.2, and get this exactly same bug.

**Comment by lianliu22** [comment]
@rkellermeyer Do you come up with a solution/fix for this bug?

**Comment by billylittlefield** [comment]
@rkellermeyer I was able to reproduce this in the sandbox and filed this issue with a little more detail: https://github.com/apache/incubator-echarts/issues/8994

FWIW, a workaround is to add `display:none` to the `<defs>` element in the SVG (if using SVG). Otherwise, removing animation (`animation: false`) in the chart options will also work.

**Comment by Ovilia** [comment]
#8994 has more detailed information for this issue. Close for duplicate.
