### ISSUE TITLE
Minor axis tick support

### ISSUE THREAD

**Issue by sonsnix** [apache/incubator-echarts#7840]
### One-line summary [问题简述]

When using a log10 y-axis, there will only be lines/tics at 1000, 100,10,1, etc.

However, I need lines/tics at 1000, 900, 800, 700, .... for my semi-log plot.

Interval etc. has no effect.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mythcyrax** [comment]
Hello,

In our (dev team from a big-ish company) decision to use this tool or not, we have a showstopper, and this is one of them: not being able to display minor ticks.
Is this prioritized for a release in the near future?
If not, we have 2 options (both are painful for us):
- choose another library than echarts
- contribute to your source code in order to get minor ticks 

I would appreciate very much if this 'enhancement' would be targeted for implementation in the near future (months).

Cheers!

**Comment by pissang** [comment]
Hi @mythcyrax We are planning to implement this feature in the version 4.6.0. Which will be released at the beginning of December.

**Comment by pissang** [comment]
Added in the https://github.com/apache/incubator-echarts/pull/11705 . Will be released in this version
