### ISSUE TITLE
Echarts 4.0 Tree: Color of leaf nodes in tree not work

### ISSUE THREAD

**Issue by rogerlh** [apache/incubator-echarts#8048]
### One-line summary [问题简述]
如option所示，把叶子节点的border设为黄色，节点本身颜色设为红色。结果是叶子节点的border被正确设置为黄色，然而非叶子节点被设置为了红色，叶子节点颜色没变。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
应该是叶子节点的颜色被设置为红色，border设置为黄色。而不会影响到非叶子

### ECharts option [ECharts配置项]

```javascript
option ={
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'tree',

                data: [data],

                top: '1%',
                left: '7%',
                bottom: '1%',
                right: '20%',

                symbolSize: 12,

                label: {
                    normal: {
                        position: 'left',
                        verticalAlign: 'middle',
                        align: 'right',
                        fontSize: 9
                    }
                },

                leaves: {
                    label: {
                        normal: {
                            position: 'right',
                            verticalAlign: 'middle',
                            align: 'left'
                        }
                    },
                    itemStyle: {
                        color: 'red',
                        borderColor: 'yellow',
                    }
                },

                expandAndCollapse: true,
                animationDuration: 550,
                animationDurationUpdate: 750
            }
        ]
    }

```

### Other comments [其他信息]

![qq 20180328235834](https://user-images.githubusercontent.com/9689265/38041344-0eab8b78-32e4-11e8-9853-7904293dc9d4.png)

**Comment by deqingli** [comment]
你好，这个问题，后续我会跟进，谢谢你的反馈

**Comment by deqingli** [comment]
@rogerlh This is not a bug, the color of the node is used to represent the expansion and collapse of the current subtree, so when a subtree is collapsed, it is treated as a leaf node, which is the red color you set. When a leaf node of a non-subtree, in order to indicate that the current node has no subtree, its color is set to white. In the future, we will use some custom symbols to represent the expansion and collapse of the subtree, so there will be no confusion in the color configuration.
