### ISSUE TITLE
documentation out of sync?

### ISSUE THREAD

**Issue by ramarro123** [apache/incubator-echarts#9184]
i am reading
https://echarts.apache.org/option.html#toolbox.feature.dataZoom.icon.zoom

and i see that the default props of
toolbox.feature.dataZoom.title.back string
is
restore area zooming

but i get some chinese character that i don't understand.

also,setting it to anything doesn't produce any change.
i am using the latest npm version that's 4.2.0-rc.1

**Comment by Ovilia** [comment]
Hi, this problem is caused because we use the same demo for English and Chinese version, and for English doc, we use default value with English version.
You may download this GitHub project and run `npm i; node build/build.js --lang en` to build the English version and get the default value as the doc shows. If this is too much trouble, you may also set [title](https://echarts.apache.org/option.html#toolbox.feature.dataZoom.title.zoom) to overwrite the default values.
