### ISSUE TITLE
timeline在ie下性能问题

### ISSUE THREAD

**Issue by saojun1024** [apache/incubator-echarts#9258]
### One-line summary [问题简述]
横轴为time时，大数据量（例如一天86000秒）时，通过定时器去获取后台数据更新时，ie10 11性能卡顿，导致系统页面菜单点击有时比较卡顿,
配置：
```
	      series:[
	      	{
	      	name   : 'tps',
	        type   : 'line',          
                progressive:10,
	        sampling: 'average',
	        symbol : 'none',
                showSymbol: false,
                hoverAnimation: false,
	        lineStyle:{normal:{width:1,color:'#409EFF'}},  //定义线条颜色(蓝色)
			      data:allDatas,
			      areaStyle:{                                    //线条下面填充颜色
				color: {
			           type: 'linear',
				   x: 0.5,
			           y: 0.5,
				   r: 0.5,
				 colorStops: [{
				    offset: 0, color: '#409EFF' // 0% 处的颜色
				     }, {
				    offset: 1, color: '#409EFF' // 100% 处的颜色
				 }],
				globalCoord: true
			        }
			     }	
	      	}
	      ]
```
我也尝试过将ie通过svg方式去渲染，但是还是无果。
还有为什么增量渲染技术，有没有什么直接添加数据的函数方法，为什么还需要setOption({data:myData})

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
环境
IE10 IE11
echarts 4

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sxmpasch** [comment]
You can reproduce this on any browser. 
Example: 
- https://ecomfe.github.io/echarts-examples/public/editor.html?c=dynamic-data2
- change setInterval function to this:
```
setInterval(function () {

    for (var i = 0; i < 50; i++) {
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 200);
```

This will happen with any chart component, because for each pixel on the screen, the average value of the points below has to be calculated - for about 1200 px every 200ms (see above).

@Ajaxluo  - What do you want to display with your chart exactly, can you please attach the rest of the Option structure? Do you need to display all values, or just a partial view?
您希望在图表中准确显示什么，是否可以附加选项结构的其余部分？您需要显示所有值，还是只显示部分视图？

**Comment by Ajaxluo** [comment]
可以在IE10或IE10下打开官方实例：
http://www.echartsjs.com/examples/editor.html?c=dynamic-data2
修改以下配置部分：
```
for (var i = 0; i < 80000; i++) {
    data.push(randomData());
}

 series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data,
        sampling:'average',
        areaStyle: {
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
            offset: 0,
            color: 'rgb(255, 158, 68)'
            }, {
            offset: 1,
            color: 'rgb(255, 70, 131)'
            }])
        },
            data: data
    }]

setInterval(function () {

    for (var i = 0; i < 5; i++) {
        data.shift();
        data.push(randomData());
    }

    myChart.setOption({
        series: [{
            data: data
        }]
    });
}, 2000);
```
修改完毕后运行，会发现官网上面顶部菜单导航点击事件就会变得卡顿，如果在配置低的IE机器甚至崩溃
在其他谷歌等浏览器均比较流畅。不必对每个x轴时间点都去绘制，准确表示一种趋势即可，有没有对ie再有优化的余地。

**Comment by sxmpasch** [comment]
@Ajaxluo - thank you for the example. If you add / remove elements, it takes time to recalculate the average value. Since you do not have zoom enabled, perhaps a data reduction during init could be everything you need:
谢谢你的例子。如果添加/删除元素，则需要时间重新计算平均值。由于您没有启用缩放，因此初始化期间的数据缩减可能是您需要的一切:

```
var it=0;
var numItems=80000;  // number of data elements
var numAvg=20;       // number of data items to reduce to one average element
for (var i = 0; i < numItems; i++) {
    data.push(randomData());
}

var dredIdx=0;
var d=0, dsum=0;
for (var i=0; i<numItems; i++) {
    dsum+=data[i].value[1];
    if ((i% numAvg)===0) {
        d=data[i];
        d.value[1]=dsum/numAvg;
        dsum=0;
        dred.push(d);
    }
}
...
setInterval(function () {

    for (var i = 0; i < 5; i++) {
        dred.shift();
        dred.push(randomData());
    }
    var s = 'test #'+it;
    it++;

    myChart.setOption({
        title: {text:s },
        series: [{
            data: dred
        }]
    });
}, 2000);

```

**Comment by 100pah** [comment]
@Ajaxluo If data amount is too large that `sampling` does not help, probably try using `scatter` chart instead of `line` chart and set [progressive](http://www.echartsjs.com/option.html#series-scatter.progressive) and [progressiveThreshold](http://www.echartsjs.com/option.html#series-scatter.progressiveThreshold) appropriately, which enables progressive rendering to avoid to block browser.

**Comment by Ajaxluo** [comment]
关于sampling 为什么不添加同时取最大值和最小值设置。例如我绘制的图有大量数据，这些数据中最小的y值点是0 ，而出现了0的点对于我来说是重要的点，是一种特征值，最大值同样如此，也是一种特征值，当前设置好像只有 min max和average ,应该有一种设置为[min,max]才更合理。而且能够有基于时间跨度的采样就更好了，例如展示一天的数据,如果每一秒都绘制点显得没有意义，应该是例如1分钟之内的采样，只取最小值和最大值，这样能够省去很多点。这样比基于1px内取样本点更好一些。当前我的做法就是人为的去自己取样本点再去setoption 。如果本身有这种配置更好了。
