### ISSUE TITLE
I cant't find "echarts.setCanvasCreator" in the document,Is there any documentation on how to use it?

### ISSUE THREAD

**Issue by AYWK** [apache/incubator-echarts#9727]
I'm going to use canvas container to create echarts. I see many people using "echarts.setCanvasCreator" on the Internet, but I can't find the related documents. Could you please help me？
Thank you very much。

**Comment by Ovilia** [comment]
Hi. This interface is not in the doc because it is generally not supposed to be used by common developers. It is used for environment similar to HTML Canvas, but not quite the same. For example, for Wechat application and so on. The parameter is a wrapper of Canvas, matching normal HTML Canvas interfaces to a modified one. See [how Wechat application uses it](https://github.com/ecomfe/echarts-for-weixin/blob/master/ec-canvas/ec-canvas.js#L50).

In your case, you just need to pass Canvas element to [init](http://echarts.apache.org/api.html#echarts.init).

```js
var canvas = document.getElementById('myCanvas');
var chart = echarts.init(canvas);
```
