### ISSUE TITLE
Add CI Integration

### ISSUE THREAD

**Issue by ClemMakesApps** [apache/incubator-echarts#9850]
As far as I can tell, there is no CI integration with this project. May I suggest we add a CI Integration? We could use CircleCI or GitLab CI (https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html)

**Comment by ClemMakesApps** [comment]
This would prevent issues like https://github.com/apache/incubator-echarts/issues/9774 from happening

**Comment by pissang** [comment]
Thanks for the suggestion!

**Comment by ClemMakesApps** [comment]
I'd be happy to help with this effort if you need assistance

**Comment by Ovilia** [comment]
@ClemMakesApps Hi Clement. We are considering adding CI support, probably Travis.

The ECharts project depends on ZRender project. When developing locally, we use a soft link in `echarts/node_modules` to the local `zrender` project.
**When using CI, how should we specify using the latest ZRender commit (rather than ZRender npm release) when building ECharts project? **
For example, there may be a new function in the latest ZRender commit, and a new ECharts commit calls this new function. Since the function is not included in the latest ZRender release on npm, `npm i zrender` will not help.

npm supports something like `npm install --save "git://github.com/username/package.git#commit"`, although I'm not sure this is helpful.
Could you please give some idea about this?

**Comment by chfw** [comment]
I think you can use 'npm link' to use any local non project.

**Comment by ClemMakesApps** [comment]
Instead of

```
"dependencies": {
  "zrender": "4.0.6"
},
```

in `master`,

if you could do

```
"dependencies": {
  "zrender": "git://github.com/ecomfe/zrender.git"
},
```

that should pull the latest `master` commit for zrender. According to https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by ClemMakesApps** [comment]
It is possible to pull in the latest ZRender `master` commit but there is a risk in doing so.

If we are pulling in the latest zrender at all times, your upstream dependency could break your CI builds in this project at any moment. This could make the CI pipeline unreliable for this project

**Comment by chfw** [comment]
Agree. With each ci test, a determined version is useful when test failure emerges.

**Comment by Ovilia** [comment]
@ClemMakesApps Is it possible to use `"zrender": "git://github.com/ecomfe/zrender.git"` for master CI, while keeping `"zrender": "4.0.6"` for release branch and hopefully for the default package.json of ECharts project?

**Comment by Ovilia** [comment]
I understand using a specific version in CI is out of the consideration of reliability. But in our situation, upstream is fully under our control and ZRender should be updated before ECharts. So depending on the latest commit should have no problem.

**Comment by ClemMakesApps** [comment]
Even though ZRender is currently under the control of ECharts core team, I still don't think it's the most optimal approach for this project. The core team for both projects could change over time, especially since one project is still under Baidu's organization while this is going through the Apache incubation process. This also makes it more difficult for contributors to contribute to ECharts because their builds may fail in the event ZRender has a breaking commit/change. In addition, this in my opinion complicates the release process (for both projects) more than it needs to be.

If we _really_ need to add ZRender `master` branch as a dependency, I would recommend adding a CI job on ZRender to check for breaking changes on ECharts on each commit. In the very least, that will ensure that each commit on ZRender doesn't indirectly break ECharts.

**Comment by Ovilia** [comment]
@ClemMakesApps Thanks Clement for the details!
We also have an internal discussion. And the conclusion is, we are going to use the npm release version on zrender in echarts project, for both master and release branch. And if there's a breaking change in zrender that echarts relies on, we will publish a non-latest version of zrender first, and then merge the related logic of echarts from a feature branch into master or release branch.
Besides, I'm working on a full doc for developing workflow so that people from the community can understand how to help.
