### ISSUE TITLE
series custom change the string value to NaN via api.value when the first string value is numeric string like '0'.

### ISSUE THREAD

**Issue by bluejiaxie** [apache/incubator-echarts#9962]
### Version
4.1.0-release

### Steps to reproduce
Data:

...
"schema": [
                {
                    "name": "DATE",
                    "type": "timestamp"
                },
                {
                    "name": "AirQualityLevel",
                    "type": "string",
                },
                ...],
"data": [
                [
                    "2015-01-01 08:00:00",
                    "0",
                    ...
                ],
                [
                    "2015-01-02 12:00:00",
                    "Slightly polluted",
                    ...
                ],
                ...
         ]
...

**************

var option = {
    ...,
    series: [{
        type: 'custom',
        renderItem: function (params, api) {
            ###Here use api.value
            ### If the first string is numeric string like "0", api.value will change return type to number type, but if next value is character string, the api.value return NaN.
            ### if the first string is character string type, api.value type still is string.
                    },
        data: data
    }]
}

### What is expected?
expected:
The type should be the same type of the set one in schema.

### What is actually happening?

Data is an array which mix character string and numeric string.
"0"    - string type
"Slightly polluted"    - string type

For the data, api.value return value as below:
api.value: 0
api.value: NaN

**Comment by 100pah** [comment]
Could I have the full `echarts option` to see what is actually happening?

**Comment by bluejiaxie** [comment]
I find an example in Gallery. Please refer to https://gallery.echartsjs.com/editor.html?c=xr1WrPou3b

1. In line 300, add '_console.log('api',api.value(2));_', and then click refresh button, the below message will display the first row.
_api 健康档案数量_

2. Change '_"健康档案数量"_' to '_"0"_' in the data section, and click refresh button again, other data will disappear in chart.

3. If just change other name to '_"0"_' except the first data (健康档案数量), all data still exist.

**Comment by bluejiaxie** [comment]
@100pah any update? Thanks.

**Comment by plainheart** [comment]
It may be not a bug, please refer to [series-custom.dimensions](https://echarts.baidu.com/option.html#series-custom.dimensions) for detailed infomation.
If you don't want to make data type changed, you need to specify data type for each data dimension manually instead of letting echarts judge automatically. After all, mechanical judgement and conversion are not always perfect.
For this case, you can add simply `dimensions` option to specify ordinal data type for each dimension.

![image](https://user-images.githubusercontent.com/26999792/53677502-c2852e80-3ceb-11e9-95b0-95f54386cb04.png)

![image](https://user-images.githubusercontent.com/26999792/53677553-b2218380-3cec-11e9-98e2-b44049a1ea84.png)

**Comment by bluejiaxie** [comment]
In fact, the input value is **"0"** (string type), is not **0** (number type). Anyway, I will try your solution and thanks for your feedback. : )

**Comment by Ovilia** [comment]
@bluejiaxie Note that in many cases in ECharts, `'0'` is considered the same as `0` to provide a better support for data from in JSON format or some other situations.
